/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PartidaRouteImport } from './routes/partida'
import { Route as CopaRouteImport } from './routes/copa'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaRoute = PartidaRouteImport.update({
  id: '/partida',
  path: '/partida',
  getParentRoute: () => rootRouteImport,
} as any)
const CopaRoute = CopaRouteImport.update({
  id: '/copa',
  path: '/copa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copa': typeof CopaRoute
  '/partida': typeof PartidaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copa': typeof CopaRoute
  '/partida': typeof PartidaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copa': typeof CopaRoute
  '/partida': typeof PartidaRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/copa' | '/partida' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/copa' | '/partida' | '/settings'
  id: '__root__' | '/' | '/copa' | '/partida' | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopaRoute: typeof CopaRoute
  PartidaRoute: typeof PartidaRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida': {
      id: '/partida'
      path: '/partida'
      fullPath: '/partida'
      preLoaderRoute: typeof PartidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copa': {
      id: '/copa'
      path: '/copa'
      fullPath: '/copa'
      preLoaderRoute: typeof CopaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopaRoute: CopaRoute,
  PartidaRoute: PartidaRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
